### PR TITLE
Adjust for end of DST 2020

### PR DESCRIPTION
**Pull request by breilly2**

### CODE REVIEW

**Comment by ehanna4** [comment]
Should it be 16 or 14? I'm seeing this previous one switching between 14 and 15 https://github.com/DataBiosphere/saturn-ui-prod-deploy/pull/4/files, but I can't quite figure out the math in my head so this may be purposeful since at some point we switched from 10 to 11?

**Review by panentheos — APPROVED** [review]
Looks good, thanks!

**Comment by breilly2** [comment]
You got it. We did ignore updating this once in order to intentionally shift the time from 10 to 11. I saw that the deploy happened at 10 AM this morning, which is one hour too early, so I shifted it to be one hour later.

**Review by ehanna4 — APPROVED** [review]
Looks good - TOL though is this now under the purview of Devops? Should we tag somebody from that team to be aware of this?

**Comment by breilly2** [comment]
Honestly, I think it's more likely us developers who are going to remember this. I had thought of it before the weekend but it didn't bubble up high enough in my priorities.

**Pull request merged**
