### PR TITLE
Adjust for start of DST 2021

### PR DESCRIPTION
**Pull request by breilly2**

### CODE REVIEW

**Review by kyuksel — APPROVED** [review]
👍🏼  assuming the time specified is according to `UTC`.
Thanks for thinking of doing this. Do/should we have a semi-annual reminder for it?

**Comment by breilly2** [comment]
@kyuksel, I made this PR in response to a reminder in the #saturn slack channel.

**Comment by kyuksel** [comment]
> I made this PR in response to a reminder in the #saturn slack channel.

@breilly2 oh cool…should that reminder be moved to #terra-ui-champions?

**Comment by breilly2** [comment]
@kyuksel Yes, that sounds like a good idea. I'll look into it.

**Pull request merged**
