### PR TITLE
[DC-317] Revert "Bump node-fetch (#25)"

### PR DESCRIPTION
**Pull request by petesantos**
This reverts commit fd7592ec488b088cee59b39a9c299d661169cfb1.

It looks like [node-fetch 3.x no longer supports the CommonJS](https://github.com/node-fetch/node-fetch#installation) / `require` syntax and only supports ESM module syntax.
I am reverting this change until we can apply and test a fix

### CODE REVIEW

**Comment by kyuksel** [comment]
Trying to understand...we depend on `node-fetch` only transitively and I used `yarn` to resolve any dependency requirements. Can't we rely on our direct dependencies to update properly to use the newer version? I feel this is no different than how we treat transitive dependencies in general. Was there a failure as a result of the bump?

**Comment by kyuksel** [comment]
Please never mind my previous comment. I confused this with another dependency bump in Terra UI repo 😕

**Review by kyuksel — APPROVED** [review]
Thanks for catching this!

Would it work if I limited the versions to < 3.x using [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions)?

**Comment by petesantos** [comment]
> Thanks for catching this!
> 
> Would it work if I limited the versions to < 3.x using [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions)?

It might, it depends on what is relying on 3.x in the dependency chain.

**Review by pshapiro4broad — APPROVED** [review]

**Review by breilly2 — APPROVED** [review]
👍  Also, I think we could move to 2.6.7 to both stay with the 2.x line and get the security patch.

**Pull request merged**
